!include "MUI2.nsh"
!include "FileFunc.nsh"

# ==========================================
# APP INFO
# ==========================================
!define APP_NAME "KWADER Sync"
!define APP_DIR "KWADER Sync"
!define COMPANY_NAME "KWADER"
!define EXE_NAME "KWADER Sync.exe"
!define APP_VERSION "1.4.9.0"

# Note: SOURCE_DIR should point to the dist folder generated by PyInstaller
!define SOURCE_DIR "..\dist\KWADER Sync"

# ==========================================
# CONFIGURATION
# ==========================================
Name "${APP_NAME}"
OutFile "KWADER_Sync_Setup_v1.4.9.exe"
InstallDir "$PROGRAMFILES\${APP_DIR}"
InstallDirRegKey HKCU "Software\${COMPANY_NAME}\${APP_NAME}" "InstallDir"
RequestExecutionLevel admin
SetCompressor /SOLID /FINAL lzma

# ==========================================
# VERSION INFO
# ==========================================
VIProductVersion "${APP_VERSION}"
VIAddVersionKey "CompanyName" "${COMPANY_NAME}"
VIAddVersionKey "FileDescription" "KWADER Sync Agent - Attendance Synchronization"
VIAddVersionKey "FileVersion" "${APP_VERSION}"
VIAddVersionKey "InternalName" "KWADER Sync"
VIAddVersionKey "LegalCopyright" "Copyright (c) 2026 KWADER"
VIAddVersionKey "ProductName" "${APP_NAME}"
VIAddVersionKey "ProductVersion" "${APP_VERSION}"

# ==========================================
# MUI INTERFACE
# ==========================================
!define MUI_ABORTWARNING
!define MUI_ICON "icon.ico"
!define MUI_UNICON "icon.ico"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES

# Finish page with "Run" checkbox
!define MUI_FINISHPAGE_RUN "$INSTDIR\${EXE_NAME}"
!define MUI_FINISHPAGE_RUN_TEXT "Run KWADER Sync now"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

# Languages
!insertmacro MUI_LANGUAGE "Arabic"
!insertmacro MUI_LANGUAGE "English"

# ==========================================
# INITIALIZATION
# ==========================================
Function .onInit
  # Ensure any existing processes are forcefully stopped before installation starts
  nsExec::Exec 'taskkill /F /IM "${EXE_NAME}" /T'
  nsExec::Exec 'taskkill /F /IM "whatsapp-node.exe" /T'
  Sleep 1000
FunctionEnd

# ==========================================
# INSTALLER SECTIONS
# ==========================================
Section "Install"
  # Terminate existing processes to prevent file locks during silent update
  nsExec::Exec 'taskkill /F /IM "${EXE_NAME}" /T'
  nsExec::Exec 'taskkill /F /IM "whatsapp-node.exe" /T'
  Sleep 1000

  SetOutPath "$INSTDIR"
  File /r "${SOURCE_DIR}\*"

  # Grant Modify permissions to Users so future OTA updates can update smoothly
  nsExec::Exec 'icacls "$INSTDIR" /grant Users:(OI)(CI)M /T /C /Q'

  WriteRegStr HKCU "Software\${COMPANY_NAME}\${APP_NAME}" "InstallDir" "$INSTDIR"
  WriteUninstaller "$INSTDIR\Uninstall.exe"

  # Shortcuts
  CreateDirectory "$SMPROGRAMS\${APP_NAME}"
  CreateShortcut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}"
  CreateShortcut "$SMPROGRAMS\${APP_NAME}\Uninstall ${APP_NAME}.lnk" "$INSTDIR\Uninstall.exe"
  CreateShortcut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}"
  
  # Add to Add/Remove Programs
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayName" "${APP_NAME}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayIcon" "$INSTDIR\${EXE_NAME}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "Publisher" "${COMPANY_NAME}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayVersion" "${APP_VERSION}"

  # Auto-start with Windows (Run key)
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "${APP_NAME}" '"$INSTDIR\${EXE_NAME}" --hidden'

  # Auto-relaunch application on silent background updates (OTA) — visible on desktop
  IfSilent is_silent not_silent
  is_silent:
    Exec '"$INSTDIR\${EXE_NAME}"'
  not_silent:
SectionEnd

# ==========================================
# UNINSTALLER SECTION
# ==========================================
Section "Uninstall"
  # Remove Shortcuts
  Delete "$DESKTOP\${APP_NAME}.lnk"
  Delete "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk"
  Delete "$SMPROGRAMS\${APP_NAME}\Uninstall ${APP_NAME}.lnk"
  RMDir "$SMPROGRAMS\${APP_NAME}"

  # Remove Installation Files
  Delete "$INSTDIR\Uninstall.exe"
  RMDir /r "$INSTDIR"

  # Remove AppData / Configurations
  RMDir /r "$APPDATA\sync-agent"

  # Remove Registry entries
  DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "${APP_NAME}"
  DeleteRegKey HKCU "Software\${COMPANY_NAME}\${APP_NAME}"
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"
SectionEnd
