!include "MUI2.nsh"
!include "FileFunc.nsh"

# ==========================================
# APP INFO
# ==========================================
!define APP_NAME "KWADER Sync"
!define APP_DIR "KWADER Sync"
!define COMPANY_NAME "KWADER"
!define EXE_NAME "KWADER Sync.exe"
!define APP_VERSION "1.6.5.0"

# Note: SOURCE_DIR should point to the dist folder generated by PyInstaller
!define SOURCE_DIR "..\dist\KWADER Sync"

# ==========================================
# CONFIGURATION
# ==========================================
Name "${APP_NAME}"
OutFile "..\installer\KWADER_Sync_Setup_v1.6.5.exe"
InstallDir "$PROGRAMFILES\${APP_DIR}"
InstallDirRegKey HKCU "Software\${COMPANY_NAME}\${APP_NAME}" "InstallDir"

# user = asInvoker manifest (no UAC required for OTA silent updates)
# Fresh installs self-elevate in .onInit if Program Files is not writable
RequestExecutionLevel user

SetCompressor /SOLID /FINAL lzma

# ==========================================
# VERSION INFO
# ==========================================
VIProductVersion "${APP_VERSION}"
VIAddVersionKey "CompanyName" "${COMPANY_NAME}"
VIAddVersionKey "FileDescription" "KWADER Sync Agent - Attendance Synchronization"
VIAddVersionKey "FileVersion" "${APP_VERSION}"
VIAddVersionKey "InternalName" "KWADER Sync"
VIAddVersionKey "LegalCopyright" "Copyright (c) 2026 KWADER"
VIAddVersionKey "ProductName" "${APP_NAME}"
VIAddVersionKey "ProductVersion" "${APP_VERSION}"

# ==========================================
# MUI INTERFACE
# ==========================================
!define MUI_ABORTWARNING
!define MUI_ICON "icon.ico"
!define MUI_UNICON "icon.ico"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES

# Finish page with "Run" checkbox
!define MUI_FINISHPAGE_RUN "$INSTDIR\${EXE_NAME}"
!define MUI_FINISHPAGE_RUN_TEXT "Run KWADER Sync now"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

# Languages
!insertmacro MUI_LANGUAGE "Arabic"
!insertmacro MUI_LANGUAGE "English"

# ==========================================
# INITIALIZATION
# ==========================================
Function .onInit
  # If silent (OTA update), proceed without elevation
  IfSilent is_silent

  # Interactive fresh install: check if install directory is writable
  ClearErrors
  CreateDirectory "$PROGRAMFILES\${APP_DIR}"
  FileOpen $0 "$PROGRAMFILES\${APP_DIR}\.perm_test" w
  IfErrors need_elevation
  FileClose $0
  Delete "$PROGRAMFILES\${APP_DIR}\.perm_test"
  Goto is_silent

need_elevation:
  # Relaunch elevated for fresh installation
  ExecShell "runas" "$EXEPATH" ""
  Quit

is_silent:
  # Silent OTA: Python app already exited and terminated child processes cleanly.
  # Only run taskkill if running interactively.
  IfSilent skip_init_kill
  nsExec::Exec 'taskkill /F /IM "${EXE_NAME}" /T'
  nsExec::Exec 'taskkill /F /IM "whatsapp-node.exe" /T'
  Sleep 1000
skip_init_kill:
FunctionEnd

# ==========================================
# INSTALLER SECTIONS
# ==========================================
Section "Install"
  # Only run process cleanup if interactive
  IfSilent skip_install_kill
  nsExec::Exec 'taskkill /F /IM "${EXE_NAME}" /T'
  nsExec::Exec 'taskkill /F /IM "whatsapp-node.exe" /T'
  Sleep 1000
skip_install_kill:

  SetOutPath "$INSTDIR"
  File /r "${SOURCE_DIR}\*"

  # Grant Modify permissions on fresh install; skip during silent OTA to avoid CMD window flash
  IfSilent skip_icacls
  nsExec::Exec 'icacls "$INSTDIR" /grant "*S-1-5-32-545:(OI)(CI)M" /T /C /Q'
  nsExec::Exec 'icacls "$INSTDIR" /grant "Users:(OI)(CI)M" /T /C /Q'
skip_icacls:

  # Registry - use HKCU (no admin required) for OTA compatibility
  WriteRegStr HKCU "Software\${COMPANY_NAME}\${APP_NAME}" "InstallDir" "$INSTDIR"
  WriteUninstaller "$INSTDIR\Uninstall.exe"

  # Shortcuts
  CreateDirectory "$SMPROGRAMS\${APP_NAME}"
  CreateShortcut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}"
  CreateShortcut "$SMPROGRAMS\${APP_NAME}\Uninstall ${APP_NAME}.lnk" "$INSTDIR\Uninstall.exe"
  CreateShortcut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${EXE_NAME}"

  # Add to Add/Remove Programs (HKCU - no admin required)
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayName" "${APP_NAME}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayIcon" "$INSTDIR\${EXE_NAME}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "Publisher" "${COMPANY_NAME}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayVersion" "${APP_VERSION}"

  # Auto-start with Windows (HKCU)
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "${APP_NAME}" '"$INSTDIR\${EXE_NAME}" --hidden'

  # Auto-relaunch on silent OTA update
  IfSilent is_silent not_silent
  is_silent:
    Exec '"$INSTDIR\${EXE_NAME}"'
  not_silent:
SectionEnd

# ==========================================
# UNINSTALLER SECTION
# ==========================================
Section "Uninstall"
  # Remove Shortcuts
  Delete "$DESKTOP\${APP_NAME}.lnk"
  Delete "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk"
  Delete "$SMPROGRAMS\${APP_NAME}\Uninstall ${APP_NAME}.lnk"
  RMDir "$SMPROGRAMS\${APP_NAME}"

  # Remove Installation Files
  Delete "$INSTDIR\Uninstall.exe"
  RMDir /r "$INSTDIR"

  # Remove AppData / Configurations
  RMDir /r "$APPDATA\sync-agent"

  # Remove Registry entries (HKCU)
  DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "${APP_NAME}"
  DeleteRegKey HKCU "Software\${COMPANY_NAME}\${APP_NAME}"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"
SectionEnd
